import { MaterialFamily, MaterialFamilyId, CreativeMaterialDefinition } from "./types";

export const MATERIAL_FAMILIES: Record<MaterialFamilyId, MaterialFamily> = {
  artisan_leather: {
    id: "artisan_leather",
    name: "Artisan Leather Craft & Restoration",
    description: "Bộ chất liệu da mộc thủ công, đường chỉ may yên ngựa, dấu dập nhiệt và vệt sáng quét nổi chất liệu",
    defaultSurface: "leather",
    defaultMark: "circle",
    defaultPhysical: "stamp",
    defaultLight: "specular_sweep",
    defaultFoley: "leather_rub",
    tags: ["leather", "craft", "asmr", "handmade", "shoes", "restoration"],
  },
  organic_farm: {
    id: "organic_farm",
    name: "Organic Farm & Dalat Lifestyle",
    description: "Bộ chất liệu giấy Kraft mộc mạc, băng keo Washi tape và nét gạch vẽ tay gần gũi thiên nhiên",
    defaultSurface: "torn_paper",
    defaultMark: "underline",
    defaultPhysical: "tape",
    defaultLight: "subtle_grain",
    defaultFoley: "paper_tear",
    tags: ["farm", "dalat", "nature", "organic", "harvest", "lifestyle"],
  },
  product_showcase: {
    id: "product_showcase",
    name: "Product Commerce & Technical Showcase",
    description: "Bộ thông số kỹ thuật, thước đo milimet, con dấu chứng nhận chất lượng, slider trước/sau và tag giá",
    defaultSurface: "none",
    defaultMark: "dimension",
    defaultPhysical: "price_badge",
    defaultLight: "specular_sweep",
    defaultFoley: "stamp_press",
    tags: ["product", "showcase", "ecommerce", "dimension", "specs", "price", "before_after"],
  },
  editorial_look: {
    id: "editorial_look",
    name: "Editorial Lookbook & Fashion",
    description: "Bộ chất liệu phong cách tạp chí thời trang, hạt phim hữu cơ, kẹp giấy kim loại và vệt sáng mượt",
    defaultSurface: "fabric",
    defaultMark: "highlight",
    defaultPhysical: "paper_clip",
    defaultLight: "soft_glow",
    defaultFoley: "clip_click",
    tags: ["fashion", "lookbook", "editorial", "minimal", "luxury"],
  },
};

export const CORE_CREATIVE_MATERIALS: CreativeMaterialDefinition[] = [
  {
    id: "leather_stitch_detail",
    name: "Artisan Saddle Stitch",
    description: "Mũi may chỉ xiên 45 độ thủ công chạy dọc mép phân cảnh",
    category: "surface",
    isProcedural: true,
    visual: {
      surface: "leather",
      primaryColor: "#E6C687",
      accentColor: "#2A1810",
      opacity: 0.95,
    },
    motion: {
      entrance: "draw_in",
      durationFrames: 20,
      delayFrames: 4,
      springDamping: 22,
      springStiffness: 90,
    },
    sonic: {
      foleyType: "stitch_pull",
      gain: 0.75,
      pitchVariation: 0.05,
      timingOffsetFrames: 0,
    },
  },
  {
    id: "hand_drawn_focus_circle",
    name: "Hand-Drawn Focus Circle",
    description: "Vòng tròn vẽ tay khoanh điểm nhấn chi tiết đắt giá",
    category: "mark",
    isProcedural: true,
    visual: {
      mark: "circle",
      primaryColor: "#FFE600",
      opacity: 0.9,
    },
    motion: {
      entrance: "draw_in",
      durationFrames: 18,
      delayFrames: 6,
      springDamping: 18,
      springStiffness: 85,
    },
    sonic: {
      foleyType: "none",
      gain: 0,
      pitchVariation: 0,
      timingOffsetFrames: 0,
    },
  },
  {
    id: "hand_drawn_arrow_mark",
    name: "Hand-Drawn Pencil Arrow",
    description: "Mũi tên chì nháp uốn cong chỉ thẳng vào điểm nhấn",
    category: "mark",
    isProcedural: true,
    visual: {
      mark: "arrow",
      primaryColor: "#FFE600",
      opacity: 0.9,
    },
    motion: {
      entrance: "draw_in",
      durationFrames: 16,
      delayFrames: 8,
      springDamping: 18,
      springStiffness: 90,
    },
    sonic: {
      foleyType: "none",
      gain: 0,
      pitchVariation: 0,
      timingOffsetFrames: 0,
    },
  },
  {
    id: "hand_drawn_check_mark",
    name: "Hand-Drawn Check Mark",
    description: "Dấu tick vẽ tay xác thực chất lượng hoặc mẹo chuẩn",
    category: "mark",
    isProcedural: true,
    visual: {
      mark: "check_mark",
      primaryColor: "#4ADE80",
      opacity: 0.95,
    },
    motion: {
      entrance: "draw_in",
      durationFrames: 14,
      delayFrames: 4,
      springDamping: 16,
      springStiffness: 100,
    },
    sonic: {
      foleyType: "none",
      gain: 0,
      pitchVariation: 0,
      timingOffsetFrames: 0,
    },
  },
  {
    id: "kraft_washi_tape_accent",
    name: "Kraft Washi Tape",
    description: "Băng keo dán giấy Kraft mờ 2 đầu thẻ chú thích",
    category: "physical",
    isProcedural: true,
    visual: {
      physicalElement: "tape",
      primaryColor: "rgba(220, 195, 155, 0.78)",
      opacity: 0.85,
      rotationDeg: -4,
    },
    motion: {
      entrance: "tape_stick",
      durationFrames: 15,
      delayFrames: 2,
      springDamping: 14,
      springStiffness: 110,
    },
    sonic: {
      foleyType: "paper_tear",
      gain: 0.6,
      pitchVariation: 0.04,
      timingOffsetFrames: 2,
    },
  },
  {
    id: "metallic_paper_clip",
    name: "Metallic Paper Clip",
    description: "Kẹp giấy kim loại đính kèm thẻ ảnh hoặc ghi chú",
    category: "physical",
    isProcedural: true,
    visual: {
      physicalElement: "paper_clip",
      primaryColor: "#D8D8D8",
      opacity: 0.95,
    },
    motion: {
      entrance: "stamp_down",
      durationFrames: 12,
      delayFrames: 3,
      springDamping: 14,
      springStiffness: 120,
    },
    sonic: {
      foleyType: "clip_click",
      gain: 0.7,
      pitchVariation: 0.05,
      timingOffsetFrames: 3,
    },
  },
  {
    id: "leather_deboss_stamp",
    name: "Leather Deboss Stamp",
    description: "Dấu dập chìm nhiệt độ sâu 3D trên bề mặt chất liệu",
    category: "physical",
    isProcedural: true,
    visual: {
      physicalElement: "stamp",
      primaryColor: "#8B4513",
      opacity: 0.9,
    },
    motion: {
      entrance: "stamp_down",
      durationFrames: 16,
      delayFrames: 8,
      springDamping: 12,
      springStiffness: 140,
    },
    sonic: {
      foleyType: "stamp_press",
      gain: 0.9,
      pitchVariation: 0.03,
      timingOffsetFrames: 8,
    },
  },
  {
    id: "before_after_slider_card",
    name: "Before/After Comparison Slider",
    description: "Thanh trượt so sánh phân chia màn hình Trước và Sau phục hồi",
    category: "physical",
    isProcedural: true,
    visual: {
      physicalElement: "before_after",
      primaryColor: "#FFE600",
      opacity: 0.95,
    },
    motion: {
      entrance: "slide_split",
      durationFrames: 45,
      delayFrames: 6,
      springDamping: 16,
      springStiffness: 100,
    },
    sonic: {
      foleyType: "whoosh_soft",
      gain: 0.8,
      pitchVariation: 0.04,
      timingOffsetFrames: 6,
    },
  },
  {
    id: "price_tag_badge_card",
    name: "Commercial Price Tag & Discount Badge",
    description: "Tag giá thương mại kèm tem giảm giá và viền nổi khối",
    category: "physical",
    isProcedural: true,
    visual: {
      physicalElement: "price_badge",
      primaryColor: "#FFE600",
      accentColor: "#D90429",
      opacity: 0.95,
    },
    motion: {
      entrance: "stamp_down",
      durationFrames: 15,
      delayFrames: 5,
      springDamping: 14,
      springStiffness: 110,
    },
    sonic: {
      foleyType: "stamp_press",
      gain: 0.8,
      pitchVariation: 0.04,
      timingOffsetFrames: 5,
    },
  },
  {
    id: "specular_surface_light_sweep",
    name: "Specular Surface Light Sweep",
    description: "Vệt sáng quét mượt làm nổi vân nổi khối chất liệu",
    category: "light",
    isProcedural: true,
    visual: {
      light: "specular_sweep",
      primaryColor: "rgba(255, 255, 255, 0.45)",
      opacity: 0.7,
    },
    motion: {
      entrance: "sweep_through",
      durationFrames: 25,
      delayFrames: 10,
      springDamping: 20,
      springStiffness: 100,
    },
    sonic: {
      foleyType: "none",
      gain: 0,
      pitchVariation: 0,
      timingOffsetFrames: 0,
    },
  },
  {
    id: "surface_organic_grain_layer",
    name: "Organic Surface Grain",
    description: "Hạt phim hữu cơ siêu mịn tăng độ điện ảnh và ấm áp",
    category: "light",
    isProcedural: true,
    visual: {
      light: "subtle_grain",
      opacity: 0.04,
    },
    motion: {
      entrance: "soft_fade",
      durationFrames: 10,
      delayFrames: 0,
      springDamping: 20,
      springStiffness: 100,
    },
    sonic: {
      foleyType: "none",
      gain: 0,
      pitchVariation: 0,
      timingOffsetFrames: 0,
    },
  },
  {
    id: "torn_paper_kraft_card",
    name: "Torn Paper Kraft Container",
    description: "Thẻ giấy Kraft xé viền răng cưa tự nhiên",
    category: "surface",
    isProcedural: true,
    visual: {
      surface: "torn_paper",
      primaryColor: "#FAF4E8",
      opacity: 0.95,
    },
    motion: {
      entrance: "draw_in",
      durationFrames: 15,
      delayFrames: 3,
      springDamping: 15,
      springStiffness: 95,
    },
    sonic: {
      foleyType: "paper_tear",
      gain: 0.7,
      pitchVariation: 0.05,
      timingOffsetFrames: 3,
    },
  },
];
