const fs = require("fs");
const path = require("path");

const BACKLOG_PATH = path.join(__dirname, "../config/unmapped_styles_backlog.json");

/**
 * Log an unmapped creative style name from AI prompt output into backlog
 * @param {string} styleName - The style name generated by AI
 * @param {string} sampleText - Example text using this style
 * @param {string} mappedFallback - The temporary fallback card used
 */
function logUnmappedStyle(styleName, sampleText = "", mappedFallback = "vibrant_yellow_sticker") {
  if (!styleName || typeof styleName !== "string") return;

  const normalizedKey = styleName.trim().toLowerCase();
  let backlog = {};

  try {
    if (fs.existsSync(BACKLOG_PATH)) {
      const content = fs.readFileSync(BACKLOG_PATH, "utf8");
      backlog = JSON.parse(content);
    }
  } catch (e) {
    backlog = {};
  }

  const timestamp = new Date().toISOString();
  if (backlog[normalizedKey]) {
    backlog[normalizedKey].occurrences = (backlog[normalizedKey].occurrences || 1) + 1;
    backlog[normalizedKey].last_requested = timestamp;
    if (sampleText && !backlog[normalizedKey].samples.includes(sampleText)) {
      backlog[normalizedKey].samples.push(sampleText);
    }
  } else {
    backlog[normalizedKey] = {
      style_name: styleName.trim(),
      occurrences: 1,
      first_requested: timestamp,
      last_requested: timestamp,
      mapped_fallback: mappedFallback,
      samples: sampleText ? [sampleText] : [],
    };
  }

  try {
    const configDir = path.dirname(BACKLOG_PATH);
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }
    fs.writeFileSync(BACKLOG_PATH, JSON.stringify(backlog, null, 2), "utf8");
  } catch (e) {
    console.error("[UnmappedStyleLogger] Failed to save backlog:", e);
  }
}

module.exports = {
  logUnmappedStyle,
  BACKLOG_PATH,
};
